---
name: Manuel Trigger
 # Allows you to run this workflow manually from the Actions tab
on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - develop
    paths:
      - oamd-app/frontend

jobs:
  build:
    runs-on: [self-hosted, edso-node-builder]
    environment:
      name: OAMD
    steps:
      - uses: actions/checkout@v4

      - name: podman login
        run: podman login imagehub.cdc.gov:6989 -u "${{ secrets.IMAGEHUB_USERNAME }}" -p "${{ secrets.IMAGEHUB_PASSWORD }}"

      - name: build image
        working-directory: oamd-app/frontend
        run: podman build . -t oamd-app/frontend
